[package]
name = "bh_mhd"
version = "0.1.0"
authors = ["Sean Purcell <iburinoc@gmail.com>"]

[dependencies]
glium = "0.13.5"
cgmath = "0.7.0"
time = "0.1.34"
rand = "*"

[lib]
name = "bh_mhd"
path = "src/lib.rs"

[[bin]]
name = "bh_mhd_test"
path = "src/test.rs"

